# Generated by Django 4.2.3 on 2024-02-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_post_coverimage_alter_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='subject',
        ),
    ]
