# Generated by Django 4.2.3 on 2024-02-07 18:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0005_remove_comments_ip_remove_comments_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
