# Generated by Django 4.2.3 on 2023-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0007_alter_notes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
