# Generated by Django 4.2.3 on 2024-02-07 18:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0009_alter_notes_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
