# Generated by Django 4.2.3 on 2024-02-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0010_alter_notes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Description',
            field=models.CharField(max_length=500),
        ),
    ]
